/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uisrael.mvc.vista;

import com.uisrael.mvc.controller.FacturaController;
import com.uisrael.mvc.daoImpl.DaoDetalle;
import com.uisrael.mvc.daoImpl.DaoFactura;
import com.uisrael.mvc.entidades.Factura;
import java.util.ArrayList;
import java.util.LinkedList;
import java.util.List;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Facturasview extends javax.swing.JFrame {

    /**
     * Creates new form Facturas
     */
    private DefaultTableModel modeloFactura;
    private FacturaController contollerFactura;
    private List<Factura> facturas;

    public Facturasview() {
        initComponents();
        init();
        initData();
    }

    private void init() {
        //crear columnas de la tabla

        if (modeloFactura == null) {
            modeloFactura = new DefaultTableModel();
        } else {
            modeloFactura.getDataVector().removeAllElements();
            modeloFactura.fireTableDataChanged();
        }

        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("Pk");
        columnas.add("Codigo");
        columnas.add("Cliente");
        columnas.add("Fecha");
        columnas.add("Total");
        for (Object columna : columnas) {
            modeloFactura.addColumn(columna);
        }

    }

    private void initData() {
        if (facturas == null) {
            facturas = new LinkedList<>();
        } else {
            facturas.clear();
        }
        contollerFactura = FacturaController.getInstance();
        facturas = contollerFactura.getFacturas();
        int contFilas = facturas.size();
        Object[] fila = new Object[5];
        int cont = 0;
        for (Factura fact : facturas) {
            fila[0] = fact.getId_factura();
            fila[1] = fact.getCodigo();
            fila[2] = fact.getUsuario().toString();
            fila[3] = fact.getFecha();
            fila[4] = fact.getTotal();
            modeloFactura.addRow(fila);
        }
        dt_facturas.setModel(modeloFactura);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        dt_facturas = new javax.swing.JTable();
        btnAgregar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dt_facturas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dt_facturas.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dt_facturasMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(dt_facturas);

        btnAgregar.setText("Agregar");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 12)); // NOI18N
        jLabel1.setText("SISTEMA DE REGISTRO DE FACTURAS");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 575, Short.MAX_VALUE)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnAgregar)
                        .addGap(0, 0, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(layout.createSequentialGroup()
                .addGap(179, 179, 179)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 42, Short.MAX_VALUE)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 199, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(btnAgregar)
                .addGap(33, 33, 33))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        this.hide();
        Facturaview factura = new Facturaview(new Factura());
        factura.setVisible(true);
        factura.setLocationRelativeTo(null);
        factura.show();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void dt_facturasMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dt_facturasMouseClicked
        int row = dt_facturas.getSelectedRow();
        Factura factura = facturas.get(row);
        Facturaview fv = new Facturaview(factura);
        this.hide();
        fv.setVisible(true);
        fv.setLocationRelativeTo(null);
        fv.show();
    }//GEN-LAST:event_dt_facturasMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturasview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturasview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturasview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturasview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturasview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAgregar;
    private javax.swing.JTable dt_facturas;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    // End of variables declaration//GEN-END:variables
}
