/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.uisrael.mvc.vista;

import com.uisrael.mvc.controller.DetalleController;
import com.uisrael.mvc.controller.FacturaController;
import com.uisrael.mvc.controller.UsuarioController;
import com.uisrael.mvc.entidades.Detalle;
import com.uisrael.mvc.entidades.Factura;
import com.uisrael.mvc.entidades.Usuario;
import java.math.BigDecimal;
import java.util.ArrayList;
import java.util.Date;
import java.util.LinkedList;
import java.util.List;
import java.util.UUID;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author USUARIO
 */
public class Facturaview extends javax.swing.JFrame {

    /**
     * Creates new form Factura
     */
    private DefaultTableModel modeloDetalle;
    private FacturaController controllerFactura;
    private DetalleController controllerDetalle;
    private UsuarioController controllerUsuario;
    private Factura factura;
    private Detalle detalle;
    private List<Detalle> detalles;
    private boolean accion;
    private BigDecimal total;
    private boolean accionDetalle;
    private Detalle detalleSelect;

    public Facturaview() {
        initComponents();
        init();
    }

    public Facturaview(Factura factura) {
        initComponents();
        this.factura = factura;
        total = BigDecimal.ZERO;
        init();
    }

    private void init() {
        detalle = new Detalle();
        detalles = new LinkedList<>();

        if (factura.getId_factura() == 0) {
            accion = true;
        }
        btnEliminar.setVisible(!accion);
        controllerFactura = FacturaController.getInstance();
        controllerDetalle = DetalleController.getInstance();
        controllerUsuario = UsuarioController.getInstace();
        crearDataModel();
    }

    public void crearDataModel() {
        if (modeloDetalle == null) {
            modeloDetalle = new DefaultTableModel();
        } else {
            modeloDetalle.getDataVector().removeAllElements();
            modeloDetalle.fireTableDataChanged();
        }

        ArrayList<Object> columnas = new ArrayList<>();
        columnas.add("Producto");
        columnas.add("Valor");
        columnas.add("Cantidad");
        for (Object columna : columnas) {
            modeloDetalle.addColumn(columna);
        }

        dt_detalle.setModel(modeloDetalle);
        detalles = new LinkedList<>();
        if (accion == false) {
            controllerDetalle = DetalleController.getInstance();
            detalles = controllerDetalle.getDetalle(factura.getId_factura());
            txtDocumento.setText(factura.getUsuario().getDocumento());
            txtNombre.setText(factura.getUsuario().getNombre());
            txtApellido.setText(factura.getUsuario().getApellido());
            txtTelefono.setText(factura.getUsuario().getTelefono());
            txtDireccion.setText(factura.getUsuario().getDireccion());
            txtTotal.setText(factura.getTotal().toString());
            initData();
        }

    }

    private void initData() {
        int contFilas = detalles.size();
        Object[] fila = new Object[3];
        modeloDetalle.getDataVector().removeAllElements();
        modeloDetalle.fireTableDataChanged();
        for (Detalle det : detalles) {
            fila[0] = det.getProducto();
            fila[1] = det.getValor();
            fila[2] = det.getCantidad();
            modeloDetalle.addRow(fila);
        }
        modeloDetalle.fireTableDataChanged();
        detalleSelect = null;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        dt_detalle = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        txtNombreProducto = new javax.swing.JTextField();
        txtPrecio = new javax.swing.JTextField();
        spcantidad = new javax.swing.JSpinner();
        btnIngresarProducto = new javax.swing.JButton();
        jLabel9 = new javax.swing.JLabel();
        txtTotal = new javax.swing.JTextField();
        jPanel2 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        txtDocumento = new javax.swing.JTextField();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtNombre = new javax.swing.JTextField();
        txtApellido = new javax.swing.JTextField();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        txtDireccion = new javax.swing.JTextField();
        txtTelefono = new javax.swing.JTextField();
        btnGuardar = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        dt_detalle.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        dt_detalle.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                dt_detalleMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(dt_detalle);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Registro Producto", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel1.setText("Nombre producto:");

        jLabel2.setText("Cantidad:");

        jLabel3.setText("Precio:");

        spcantidad.setModel(new javax.swing.SpinnerNumberModel(0, 0, null, 1));

        btnIngresarProducto.setText("Ingresar Producto");
        btnIngresarProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnIngresarProductoActionPerformed(evt);
            }
        });

        jLabel9.setText("Total:");

        txtTotal.setEnabled(false);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(29, 29, 29)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel3)
                    .addComponent(jLabel2))
                .addGap(18, 18, 18)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtNombreProducto)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addComponent(spcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(jLabel9)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnIngresarProducto, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtNombreProducto, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(txtPrecio, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(spcantidad, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel9)
                        .addComponent(txtTotal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(34, 34, 34))
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(btnIngresarProducto)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(null, "Datos Cliente", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 11))); // NOI18N

        jLabel4.setText("Documento:");

        jLabel5.setText("Nombre:");

        jLabel6.setText("Apellido:");

        jLabel7.setText("Direccion:");

        jLabel8.setText("Telefono:");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(77, 77, 77)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel4)
                    .addComponent(jLabel5)
                    .addComponent(jLabel6))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtDocumento)
                    .addComponent(txtNombre)
                    .addComponent(txtApellido, javax.swing.GroupLayout.DEFAULT_SIZE, 139, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addGap(18, 18, 18)
                        .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, 129, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(18, 18, 18)
                        .addComponent(txtTelefono)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(22, 22, 22)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(txtDocumento, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel7)
                    .addComponent(txtDireccion, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtTelefono, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 20, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtNombre, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel5)
                        .addComponent(jLabel8)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtApellido, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        btnGuardar.setText("Guardar");
        btnGuardar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnGuardarActionPerformed(evt);
            }
        });

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCancelarActionPerformed(evt);
            }
        });

        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnGuardar)
                        .addGap(18, 18, 18)
                        .addComponent(btnEliminar)
                        .addGap(33, 33, 33)
                        .addComponent(btnCancelar))
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 526, Short.MAX_VALUE)))
                .addContainerGap(128, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 123, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnCancelar, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 23, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(btnGuardar)
                        .addComponent(btnEliminar)))
                .addGap(27, 27, 27)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 133, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(64, 64, 64))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnIngresarProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnIngresarProductoActionPerformed
        ingresarProducto();
    }//GEN-LAST:event_btnIngresarProductoActionPerformed

    private void btnGuardarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnGuardarActionPerformed
        try {
            guardar();
            cierrarPantalla();
        } catch (Exception ex) {
            Logger.getLogger(Facturaview.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_btnGuardarActionPerformed

    private String guardar() throws Exception {

        validar();
        Usuario usuario = null;

        if (accion == true) {
            usuario = new Usuario();
        } else {
            usuario = factura.getUsuario();
        }

        usuario.setDocumento(txtDocumento.getText().trim());
        usuario.setNombre(txtNombre.getText().trim());
        usuario.setApellido(txtApellido.getText().trim());
        usuario.setDireccion(txtDireccion.getText() == null ? "" : txtDireccion.getText().trim());
        usuario.setTelefono(txtTelefono.getText() == null ? "" : txtTelefono.getText().trim());
        if (usuario.getId_usuario() == 0) {
            controllerUsuario.guardar(usuario);
        } else {
            controllerUsuario.editar(usuario);
        }

        usuario = null;
        usuario = controllerUsuario.getUsuarioFindByDocumento(txtDocumento.getText().trim());
        UUID codigo = UUID.randomUUID();
        if (accion == true) {
            factura.setCodigo(codigo.toString());
        }

        factura.setFecha(new Date());
        factura.setTotal(total);
        factura.setUsuario(usuario);
        if (factura.getId_factura() == 0) {
            controllerFactura.guardar(factura);
        } else {
            controllerFactura.editar(factura);
        }

        if (factura.getId_factura() == 0) {
            factura = null;
            factura = controllerFactura.getFacturaByCodigo(codigo.toString());
        }

        for (Detalle d : detalles) {
            d.setFactura(factura);
            if (d.getId_detalle() == 0) {
                controllerDetalle.guardar(d);
            } else {
                controllerDetalle.editar(d);
            }
        }

        return null;
    }

    private String validar() {
        if (txtDocumento.getText() == null || txtDocumento.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Documento necesario");
            return null;
        }

        if (txtNombre.getText() == null || txtNombre.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Nombre necesario");
            return null;
        }
        if (txtApellido.getText() == null || txtApellido.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Apellido necesario");
            return null;
        }

        if (detalles.isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar un producto por lo menos");
            return null;
        }
        return null;
    }
    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        cierrarPantalla();

    }//GEN-LAST:event_btnCancelarActionPerformed

    private void dt_detalleMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_dt_detalleMouseClicked
        int row = dt_detalle.getSelectedRow();
        Detalle de = detalles.get(row);
        txtNombreProducto.setText(de.getProducto());
        txtPrecio.setText(de.getValor().toString());
        spcantidad.setValue(de.getCantidad());
        detalleSelect = de;
        accionDetalle = true;

    }//GEN-LAST:event_dt_detalleMouseClicked

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed

        try {
            for (Detalle det : detalles) {
                controllerDetalle.eliminar(det);
            }
            controllerFactura.eliminar(factura);
            controllerUsuario.eliminar(factura.getUsuario());
        } catch (Exception ex) {
            Logger.getLogger(Facturaview.class.getName()).log(Level.SEVERE, null, ex);
        }
        cierrarPantalla();
    }//GEN-LAST:event_btnEliminarActionPerformed

    private String ingresarProducto() {
        if (txtNombreProducto.getText() == null || txtNombreProducto.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar nombre producto");
            return null;
        }

        if (txtPrecio.getText() == null || txtPrecio.getText().isEmpty()) {
            JOptionPane.showMessageDialog(null, "Debe ingresar precio producto");
            return null;
        }
        BigDecimal valor;
        try {
            valor = new BigDecimal(txtPrecio.getText().trim());
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "El valor del precio no es correcto");
            txtPrecio.setText("");
            return null;
        }

        if ((Integer) spcantidad.getValue() == 0) {
            JOptionPane.showMessageDialog(null, "El valor de cantidad no puede ser cero");
            return null;
        }

        if (accionDetalle == false) {
            detalle = new Detalle();
            detalle.setCantidad((Integer) spcantidad.getValue());
            detalle.setProducto(txtNombreProducto.getText().trim());
            detalle.setValor(valor);
            detalles.add(detalle);
        } else {
            detalleSelect.setCantidad((Integer) spcantidad.getValue());
            detalleSelect.setProducto(txtNombreProducto.getText().trim());
            detalleSelect.setValor(valor);
        }

        accionDetalle = false;
        total = total.add(valor.multiply(new BigDecimal(detalle.getCantidad())));
        txtTotal.setText(total.toString());
        initData();
        limpiarCampos();
        return null;
    }

    private void limpiarCampos() {
        txtNombreProducto.setText("");
        txtPrecio.setText("");
        spcantidad.setValue(0);
    }

    private void cierrarPantalla() {
        this.dispose();
        Facturasview view = new Facturasview();
        view.setVisible(true);
        view.setLocationRelativeTo(null);
        view.show();
    }

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Facturaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Facturaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Facturaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Facturaview.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Facturaview().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnGuardar;
    private javax.swing.JButton btnIngresarProducto;
    private javax.swing.JTable dt_detalle;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JSpinner spcantidad;
    private javax.swing.JTextField txtApellido;
    private javax.swing.JTextField txtDireccion;
    private javax.swing.JTextField txtDocumento;
    private javax.swing.JTextField txtNombre;
    private javax.swing.JTextField txtNombreProducto;
    private javax.swing.JTextField txtPrecio;
    private javax.swing.JTextField txtTelefono;
    private javax.swing.JTextField txtTotal;
    // End of variables declaration//GEN-END:variables
}
